# Generated by Django 2.0.7 on 2018-08-28 12:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deviceman', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('num', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=40)),
                ('telephone', models.IntegerField()),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('date', models.DateField()),
                ('provider', models.ForeignKey(on_delete=False, to='stationery.provider')),
            ],
        ),
        migrations.CreateModel(
            name='stat_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='stationery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('spec', models.CharField(default='--', max_length=40)),
                ('stock_num', models.IntegerField()),
                ('stat_type', models.ForeignKey(on_delete=False, related_name='stat_type_name', to='stationery.stat_type')),
            ],
        ),
        migrations.AddField(
            model_name='purchase',
            name='stationery',
            field=models.ForeignKey(on_delete=False, to='stationery.stationery'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(default=1, on_delete=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order_record',
            name='stationery',
            field=models.ForeignKey(on_delete=False, to='stationery.stationery'),
        ),
        migrations.AddField(
            model_name='order_record',
            name='user_list',
            field=models.ForeignKey(on_delete=False, to='deviceman.user_list'),
        ),
    ]
