# Generated by Django 2.0.7 on 2018-08-28 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceman', '__first__'),
        ('stationery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.ImageField(upload_to='')),
                ('stationery', models.ForeignKey(on_delete=False, to='stationery.stationery')),
                ('user_list', models.ForeignKey(on_delete=False, to='deviceman.user_list')),
            ],
        ),
    ]
