# Generated by Django 2.0.7 on 2018-08-29 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deviceman', '__first__'),
        ('stationery', '0002_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='order_record_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('order_status', models.CharField(max_length=40)),
                ('user_list', models.ForeignKey(on_delete=False, to='deviceman.user_list')),
            ],
        ),
        migrations.CreateModel(
            name='order_record_slave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('order_record_master', models.ForeignKey(on_delete=False, to='stationery.order_record_master')),
                ('stationery', models.ForeignKey(on_delete=False, to='stationery.stationery')),
            ],
        ),
        migrations.RemoveField(
            model_name='order_record',
            name='stationery',
        ),
        migrations.RemoveField(
            model_name='order_record',
            name='user_list',
        ),
        migrations.DeleteModel(
            name='order_record',
        ),
    ]
