# Generated by Django 2.0.7 on 2018-08-30 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stationery', '0003_auto_20180829_1343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_record_slave',
            old_name='num',
            new_name='order_num',
        ),
    ]
